version: "3.9"


services:
  db:
    container_name: database
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  tg_bot:
    container_name: tg_bot
    build: .
    depends_on:
      - db
